#!/usr/bin/env node
/* ==========================================================================
 * gen-sitemap.js — single source of truth for SEO discoverability.
 *
 * Reads articles.json and emits, from data (never hand-hardcoded):
 *   1. /sitemap.xml      — every real URL, EXTENSIONLESS (matches the Cloudflare
 *                          Pages clean-URL form that is actually served; the
 *                          ".html" variants 308-redirect, so we never list them).
 *   2. index.html        — a static, crawler-visible <noscript> article directory
 *                          (all articles + category links) injected between the
 *                          SEO-INDEX:START / SEO-INDEX:END markers, so every
 *                          article has at least one static <a href> a crawler can
 *                          follow without executing JavaScript.
 *
 * Re-run after any articles.json change:  node scripts/gen-sitemap.js
 * ========================================================================== */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const ORIGIN = "https://islamicfiqhpublishing.com";

const articles = JSON.parse(fs.readFileSync(path.join(ROOT, "articles.json"), "utf8"));

// --- helpers -------------------------------------------------------------
const esc = (s) =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

// "/articles/tarikh/foo.html" -> "/articles/tarikh/foo" (extensionless, served form)
const extensionless = (url) => url.replace(/\.html$/, "");

const today = new Date().toISOString().slice(0, 10);
const maxDate = (list) =>
  list.reduce((m, a) => (a.date && a.date > m ? a.date : m), "0000-00-00") || today;

// Category registry order + Thai labels (Rule 70). Label is taken from the data
// when available so it never drifts from articles.json.
const CATEGORY_ORDER = ["nitisart", "kalam", "history", "hadith", "hajj"];
const labelFor = (key) => {
  const hit = articles.find((a) => a.categoryKey === key && a.categoryLabel);
  return hit ? hit.categoryLabel : key;
};

// --- 1. sitemap.xml ------------------------------------------------------
// Static (non-article) routes. Tool sub-pages that are noindex are omitted.
const staticRoutes = [
  { loc: "/", lastmod: maxDate(articles), changefreq: "daily", priority: "1.0" },
  ...CATEGORY_ORDER.map((key) => ({
    loc: `/pages/${key}`,
    lastmod: maxDate(articles.filter((a) => a.categoryKey === key)),
    changefreq: "weekly",
    priority: "0.8",
  })),
  { loc: "/pages/articles", lastmod: maxDate(articles), changefreq: "weekly", priority: "0.6" },
  { loc: "/pages/tools", lastmod: today, changefreq: "monthly", priority: "0.5" },
  { loc: "/pages/tools/hijri-time-machine", lastmod: today, changefreq: "monthly", priority: "0.5" },
  { loc: "/pages/tools/ijazah-network", lastmod: today, changefreq: "monthly", priority: "0.5" },
  { loc: "/pages/about", lastmod: today, changefreq: "yearly", priority: "0.3" },
];

const articleRoutes = articles.map((a) => ({
  loc: extensionless(a.url),
  lastmod: a.date || today,
  changefreq: "monthly",
  priority: "0.7",
}));

const allRoutes = [...staticRoutes, ...articleRoutes];

const urlXml = (r) =>
  `  <url>\n` +
  `    <loc>${ORIGIN}${r.loc}</loc>\n` +
  `    <lastmod>${r.lastmod}</lastmod>\n` +
  `    <changefreq>${r.changefreq}</changefreq>\n` +
  `    <priority>${r.priority}</priority>\n` +
  `  </url>`;

const sitemap =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- Generated by scripts/gen-sitemap.js — do not hand-edit. -->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  allRoutes.map(urlXml).join("\n") +
  `\n</urlset>\n`;

fs.writeFileSync(path.join(ROOT, "sitemap.xml"), sitemap);

// --- 2. static <noscript> article directory in index.html ----------------
const byDate = (a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0);

let dir = "";
for (const key of CATEGORY_ORDER) {
  const inCat = articles.filter((a) => a.categoryKey === key).sort(byDate);
  if (!inCat.length) continue;
  dir += `    <li><a href="/pages/${key}">${esc(labelFor(key))}</a>\n      <ul>\n`;
  for (const a of inCat) {
    dir += `        <li><a href="${extensionless(a.url)}">${esc(a.title)}</a></li>\n`;
  }
  dir += `      </ul>\n    </li>\n`;
}

const noscriptBlock =
  `<noscript>\n` +
  `  <nav class="seo-index" aria-label="สารบัญบทความทั้งหมด">\n` +
  `    <h2>สารบัญบทความทั้งหมด</h2>\n` +
  `    <ul>\n` +
  dir +
  `    </ul>\n` +
  `  </nav>\n` +
  `</noscript>`;

const INDEX = path.join(ROOT, "index.html");
let html = fs.readFileSync(INDEX, "utf8");
const START = "<!-- SEO-INDEX:START";
const END = "<!-- SEO-INDEX:END -->";
const sIdx = html.indexOf(START);
const eIdx = html.indexOf(END);
if (sIdx === -1 || eIdx === -1) {
  console.error("ERROR: SEO-INDEX markers not found in index.html — aborting injection.");
  process.exit(1);
}
const startLineEnd = html.indexOf("-->", sIdx) + 3;
html = html.slice(0, startLineEnd) + "\n" + noscriptBlock + "\n" + html.slice(eIdx);
fs.writeFileSync(INDEX, html);

// --- report --------------------------------------------------------------
const counts = CATEGORY_ORDER.map((k) => `${k}=${articles.filter((a) => a.categoryKey === k).length}`).join(", ");
console.log(`sitemap.xml: ${allRoutes.length} <url> (static ${staticRoutes.length} + articles ${articleRoutes.length})`);
console.log(`index.html: injected ${articles.length} article links + ${CATEGORY_ORDER.length} category links (${counts})`);
